### ISSUE TITLE
没有办法获取到点击的元素嘛?

### ISSUE THREAD

**Issue by EggsBlue** [M-finder/Layim-contextmenu#1]
指定右键菜单,无法获取到触发事件的元素嘛?
`menu: [
                        {
                            text: "删除",
                            callback: function (obj) {
                                alert("删除");
                                console.log(obj);  //打印undefined
                            }
                        }
                    ]`

**Comment by m-finder** [comment]
我给封装在里边了


![image](https://user-images.githubusercontent.com/27805032/33753206-0f0d1bfa-dc21-11e7-945f-16e5ed4538ce.png)

**Comment by m-finder** [comment]
已解决
